# Dockerfile.render
FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# This start script will be created next
CMD ["bash", "start.sh"]